model_name_or_path: Qwen/Qwen2-VL-7B-Instruct
bf16: true
cutoff_len: 1024
dataset: all_attrs
dataset_dir: /iitjhome/m23csa016/meesho_code/LLaMA-Factory/data/
ddp_timeout: 180000000
do_train: true
eval_steps: 200
eval_strategy: steps
finetuning_type: lora
flash_attn: auto
gradient_accumulation_steps: 4
include_num_input_tokens_seen: true
learning_rate: 5.0e-05
logging_steps: 5
lora_alpha: 16
lora_dropout: 0
lora_rank: 8
lora_target: all
lr_scheduler_type: reduce_lr_on_plateau
max_grad_norm: 1.0
max_samples: 12000
num_train_epochs: 6.0
optim: adamw_torch
output_dir: /scratch/data/m23csa016/meesho_data/finetuning/all_attrs
packing: false
per_device_eval_batch_size: 8
per_device_train_batch_size: 8
plot_loss: true
preprocessing_num_workers: 16
quantization_bit: 8
quantization_method: bitsandbytes
report_to: none
save_steps: 200
stage: sft
template: qwen2_vl
val_size: 0.1
warmup_steps: 0